# Support the author by using the funding Links below
# Developed and maintained by Java James with the help of awesome contributors.
# GitHub Sponsors: https://github.com/sponsors/java-james
# Buy Me a Coffee: https://buymeacoffee.com/javajames
github: java-james
buy_me_a_coffee: javajames
# Your support means a lot to me to continue the development of open source project like this.
# Sponsoring this project means a lot to me. Your support helps me to continue building great
# open-source projects just like this.|